/* bin2c: emit a file's bytes as a C array on stdout.
 * Usage: bin2c <input-file> <array-name>
 */
#include <stdio.h>

int main(int argc, char **argv)
{
    FILE *f;
    int c;
    unsigned long n = 0;

    if (argc != 3) {
        fprintf(stderr, "usage: %s <input-file> <array-name>\n", argv[0]);
        return 1;
    }
    f = fopen(argv[1], "rb");
    if (!f) {
        perror(argv[1]);
        return 1;
    }
    printf("/* generated by bin2c from %s -- do not edit */\n", argv[1]);
    printf("const unsigned char %s[] = {", argv[2]);
    while ((c = fgetc(f)) != EOF) {
        if (n % 16 == 0) printf("\n  ");
        printf("0x%02x,", (unsigned char)c);
        n++;
    }
    printf("\n};\n");
    printf("const unsigned long %s_len = %luUL;\n", argv[2], n);
    fclose(f);
    return 0;
}
