# Generate a C header embedding a file as a byte array.
# Usage: cmake -DIN=<file> -DOUT=<header> -DNAME=<array-name> -P embed.cmake
file(READ "${IN}" hex HEX)
string(LENGTH "${hex}" hexlen)
math(EXPR len "${hexlen} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
file(WRITE "${OUT}"
    "/* generated by cmake/embed.cmake from ${IN} -- do not edit */\n"
    "const unsigned char ${NAME}[] = {${bytes}};\n"
    "const unsigned long ${NAME}_len = ${len}UL;\n")
